### ISSUE TITLE
V1 of Circuit Diagram

### ISSUE THREAD

**Issue by kjans123** [kjans123/BME590-LightDHF#19]
Hi Dr. Palmeri, here is my first attempt at the circuit diagram. I am trying to use an LM317 Adjustable Voltage Regulator (https://www.onsemi.com/pub/Collateral/LM317-D.PDF), but am not sure if I have it drawn correctly. It is used as an offset to the 0.7V voltage clipper. Does that portion of the circuit look okay?
https://github.com/kjans123/BME590-LightDHF/blob/master/Electronics/V1CircuitDiagram.pdf

**Comment by mlp6** [comment]
This is a bit overkill for what you want... we probably have Zener diodes in the lab with a breakdown voltage of 5 V that will do this much easier.  The DC offset will do it too, but in this case, too much hardware to get the voltage threshold that you want.  

What EDA software do you plan to use?

**Comment by kjans123** [comment]
Oh, sounds great! I'd totally be fine with simplifying that circuit a bit. I am planning on using Eagle.
