### ISSUE TITLE
V2 Circuit Diagram Review

### ISSUE THREAD

**Issue by kjans123** [kjans123/BME590-LightDHF#22]
Hi Dr. Palmeri, how does this circuit look? I added the Zener diode, two bypass caps in parallel on the Vcc line going into the MCU and a master switch next to the battery. 

https://github.com/kjans123/BME590-LightDHF/blob/master/Electronics/V2CircuitDiagram.pdf

**Comment by mlp6** [comment]
In general, this looks good!

**Comment by kjans123** [comment]
Great, thank you!
